version: '3.2'
services:
  mysql: 
    image: docker.io/mysql:latest
    container_name: noodb-mysql
    ports:
      - "3306:3306"
    volumes:
      - "./conf.d/:/etc/mysql/conf.d"
      - "./data:/var/lib/mysql"  #挂载目录，持久化存储
      - "./initsql:/docker-entrypoint-initdb.d"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_HOST=%"