spring:
  profiles:
    active: dev
    group:
      dev: "dev,common"
      prod: "prod,common"

# common 配置
---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: nblog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/nblog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8095
  servlet:
    context-path: /api

# 开发配置
---
spring:
  config:
    activate:
      on-profile: dev
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: debug
    com.noodb.blog.mapper: error
    com.noodb.blog: debug
article:
  imagePath:
    /Users/noodzhan/IdeaProjects/noodb/back-end/build/


# 生产配置
---
spring:
  config:
    activate:
      on-profile: prod
article:
  imagePath:
    /home/ubuntu/nblog/article-images/
